services:
    memeoirs_paymill.api:
      class: Memeoirs\PaymillBundle\API\PaymillApi
      arguments: [%memeoirs_paymill.api_private_key%]

    memeoirs_paymill.plugin:
       class: Memeoirs\PaymillBundle\Plugin\PaymillPlugin
       arguments: ['@memeoirs_paymill.api']
       tags:
            - { name: payment.plugin }

    memeoirs_paymill.event_plugin:
       class: Memeoirs\PaymillBundle\Plugin\PaymillEventPlugin
       tags:
            - { name: payment.plugin }

    memeoirs_paymill.paymill_type:
        class: Memeoirs\PaymillBundle\Form\PaymillType
        arguments: ['@translator']
        tags:
            - { name: payment.method_form_type }
            - { name: form.type, alias: paymill }

    memeoirs_paymill.extension:
      class: Memeoirs\PaymillBundle\Templating\PaymillExtension
      arguments: ['@service_container', %memeoirs_paymill.api_public_key%]
      tags:
        - { name: twig.extension }

    memeoirs_paymill.helper:
      class: Memeoirs\PaymillBundle\Templating\PaymillHelper
      arguments: ['@templating', %memeoirs_paymill.initialize_template%]
      tags:
        - { name: templating.helper }
